### PR TITLE
Handle place picker dialog on configuration change

### LINKED ISSUE #324: Place picker leaks dialog on rotation
### Description

Place picker component leaks the "Use this place?" dialog when the device is rotated from portrait to landscape.

### Steps to Reproduce

1. Start place picker demo
2. Select a location on the map so the "Use this place?" dialog is displayed on the screen
3. Rotate the device and the dialog be hidden

The following error is in the logs:

```
03-07 11:14:44.101 21644-21644/com.mapzen.places.api.sample E/WindowManager: android.view.WindowLeaked: Activity com.mapzen.places.api.internal.PlacePickerActivity has leaked window DecorView@f1a01db[] that was originally added here
                                                                                 at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
                                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                                 at android.app.Dialog.show(Dialog.java:322)
                                                                                 at com.mapzen.places.api.internal.PlacePickerActivity.showDialog(PlacePickerActivity.java:95)
                                                                                 at com.mapzen.places.api.internal.PlacePickerPresenterImpl.onLabelPicked(PlacePickerPresenterImpl.java:48)
                                                                                 at com.mapzen.places.api.internal.PlacePickerActivity.onLabelPicked(PlacePickerActivity.java:85)
                                                                                 at com.mapzen.android.graphics.LabelPickHandler$1.run(LabelPickHandler.java:37)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

### Mapzen SDK & Android Version

Mapzen Android SDK 1.3.1
Android 7.1.1

place-picker-dialog

### PR DESCRIPTION
**Pull request by ecgreb**
### Overview

Properly handle place picker dialog on configuration change so state is persisted and dialog is not leaked.

### Proposed Changes

* Converts place picker dialog from standalone `AlertDialog` to a `DialogFragment` to maintain view state.
* Add `PlaceStore` singleton to persist current selection data through configuration change when `PlacePickerPresenter` is destroyed and recreated along with `PlacePickerActivity`.
* Updates sample app to (naively) handle configuration change by preventing launching another instance of the place picker if one is already active.

Fixes #324

### CODE REVIEW

File: mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDialogFragment.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+import android.content.DialogInterface;
+import android.os.Bundle;
+
+/**
+ * Confirmation dialog shown to the user when a POI has been selected.
+ */
+public class PlaceDialogFragment extends DialogFragment implements DialogInterface.OnClickListener {
+  public static final String TAG = PlaceDialogFragment.class.getSimpleName();
+
+  private static final String ARG_NAME_TITLE = "title";
```
Comment (sarahlensing) [inline mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDialogFragment.java]: To be more consistent with the property set on the dialog and with the `setMessage` method, we should change this to `ARG_NAME_MESSAGE`

File: mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDialogFragment.java [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+  private AlertDialog dialog;
+  private PlaceDialogListener listener;
+
+  /**
+   * Create new instance of the dialog fragment.
+   *
+   * @param title text to be displayed in the dialog.
+   * @return a new instance of the dialog fragment.
+   */
+  public static PlaceDialogFragment newInstance(String title) {
```
Comment (sarahlensing) [inline mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDialogFragment.java]: Related to above, we should change the param name from `title` to `message`

File: mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDialogFragment.java (hunk 1 above)
Comment (ecgreb) [inline mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDialogFragment.java]: Good call. Updated!

File: mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDialogFragment.java (hunk 2 above)
Comment (ecgreb) [inline mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDialogFragment.java]: Also fixed
